name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version bump: patch, minor, major'
        required: true
        default: 'patch'

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: bump_version
        uses: einaregilsson/semantic-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: false
          branch: main
          version_type: ${{ github.event.inputs.version_type }}

  build:
    name: Build for amd64 and arm64
    runs-on: ubuntu-latest
    needs: bump_version
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${{ matrix.goos }}_${{ matrix.goarch }}/ghpc ./cmd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ghpc-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/${{ matrix.goos }}_${{ matrix.goarch }}/ghpc

  generate_changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      
      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      - name: Generate Changelog
        run: |
          github_changelog_generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }}
          mv CHANGELOG.md build/

      - name: Upload Changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: build/CHANGELOG.md

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, generate_changelog]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Build Artifacts (amd64)
        uses: actions/download-artifact@v2
        with:
          name: ghpc-linux-amd64
          path: build/linux_amd64/

      - name: Download Build Artifacts (arm64)
        uses: actions/download-artifact@v2
        with:
          name: ghpc-linux-arm64
          path: build/linux_arm64/

      - name: Download Changelog
        uses: actions/download-artifact@v2
        with:
          name: changelog
          path: build/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            build/linux_amd64/ghpc
            build/linux_arm64/ghpc
          body_path: build/CHANGELOG.md
