name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${{ matrix.goos }}_${{ matrix.goarch }}/ghpc-${{ matrix.goos }}-${{ matrix.goarch }}


      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghpc-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/${{ matrix.goos }}_${{ matrix.goarch }}/ghpc-${{ matrix.goos }}-${{ matrix.goarch }}

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts (linux-amd64)
        uses: actions/download-artifact@v4
        with:
          name: ghpc-linux-amd64
          path: build/linux_amd64/

      - name: Download Build Artifacts (linux-arm64)
        uses: actions/download-artifact@v4
        with:
          name: ghpc-linux-arm64
          path: build/linux_arm64/

      - name: Download Build Artifacts (darwin-amd64)
        uses: actions/download-artifact@v4
        with:
          name: ghpc-darwin-amd64
          path: build/darwin_amd64/

      - name: Download Build Artifacts (darwin-arm64)
        uses: actions/download-artifact@v4
        with:
          name: ghpc-darwin-arm64
          path: build/darwin_arm64/

      - name: Create GitHub Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GH_PAT_TOKEN }}
          draft: false
          prerelease: false
          files: |
            build/linux_amd64/ghpc-linux-amd64
            build/linux_arm64/ghpc-linux-arm64
            build/darwin_amd64/ghpc-darwin-amd64
            build/darwin_arm64/ghpc-darwin-arm64
